# Healthy Diet Cost & Affordability

----

In [1]:
import pandas as pd
import numpy as np
import psycopg2

import seaborn as sns
import matplotlib.pyplot as plt

import plotly.graph_objs as go
import plotly.offline as pyo
from sqlalchemy import create_engine

## Data Extraction - PostgresSQL Database

In [2]:
# Establishing a connection to the database.
engine = create_engine('postgresql://postgres:Thea1204%40@localhost:5432/dataengineering')

In [3]:
# Defining the SQL Query that will extract the data from the database.
query1 = "SELECT * FROM healthy_diet_affordability_1"
query2 = "SELECT * FROM healthy_diet_affordability_2"

In [4]:
# Fetch all the data needed from the database and store in a pandas dataframe.
df1 = pd.read_sql(query1, engine)
df2 = pd.read_sql(query2, engine)

In [5]:
engine.dispose()

In [6]:
df1.head(10)

,ï»¿Domain Code,Domain,Area Code (M49),Area,Element Code,Element,Item Code,Item,Year Code,Year,Unit,Value,Flag,Flag Description
0,CAHD,Cost and Affordability of a Healthy Diet (CoAHD),8,Albania,6226,Value,7004,Cost of a healthy diet (PPP dollar per person ...,2017,2017,PPP dollar per person per day,3.952,E,Estimated value
1,CAHD,Cost and Affordability of a Healthy Diet (CoAHD),8,Albania,6226,Value,7004,Cost of a healthy diet (PPP dollar per person ...,2018,2018,PPP dollar per person per day,4.051,E,Estimated value
2,CAHD,Cost and Affordability of a Healthy Diet (CoAHD),8,Albania,6226,Value,7004,Cost of a healthy diet (PPP dollar per person ...,2019,2019,PPP dollar per person per day,4.117,E,Estimated value
3,CAHD,Cost and Affordability of a Healthy Diet (CoAHD),8,Albania,6226,Value,7004,Cost of a healthy diet (PPP dollar per person ...,2020,2020,PPP dollar per person per day,4.197,E,Estimated value
4,CAHD,Cost and Affordability of a Healthy Diet (CoAHD),8,Albania,6226,Value,7007,Cost of starchy staples,2017,2017,PPP dollar per person per day,0.599,E,Estimated value
5,CAHD,Cost and Affordability of a Healthy Diet (CoAHD),8,Albania,6226,Value,7008,Cost of animal source foods,2017,2017,PPP dollar per person per day,1.204,E,Estimated value
6,CAHD,Cost and Affordability of a Healthy Diet (CoAHD),8,Albania,6226,Value,7009,"Cost of legumes, nuts and seeds",2017,2017,PPP dollar per person per day,0.441,E,Estimated value
7,CAHD,Cost and Affordability of a Healthy Diet (CoAHD),8,Albania,6226,Value,7010,Cost of vegetables,2017,2017,PPP dollar per person per day,0.707,E,Estimated value
8,CAHD,Cost and Affordability of a Healthy Diet (CoAHD),8,Albania,6226,Value,7011,Cost of fruits,2017,2017,PPP dollar per person per day,0.911,E,Estimated value
9,CAHD,Cost and Affordability of a Healthy Diet (CoAHD),8,Albania,6226,Value,7012,Cost of oils and fats,2017,2017,PPP dollar per person per day,0.089,E,Estimated value

In [7]:
df2.head(10)

,Area Code,Area Code (M49),Area,Item Code,Item,Element Code,Element,Unit,Y2017,Y2018,Y2019,Y2020
0,3,'008,Albania,7004,Cost of a healthy diet (PPP dollar per person ...,6226,Value,PPP dollar per person per day,3.952,4.051,4.117,4.197
1,3,'008,Albania,7007,Cost of starchy staples,6226,Value,PPP dollar per person per day,0.599,NaN,NaN,NaN
2,3,'008,Albania,7008,Cost of animal source foods,6226,Value,PPP dollar per person per day,1.204,NaN,NaN,NaN
3,3,'008,Albania,7009,"Cost of legumes, nuts and seeds",6226,Value,PPP dollar per person per day,0.441,NaN,NaN,NaN
4,3,'008,Albania,7010,Cost of vegetables,6226,Value,PPP dollar per person per day,0.707,NaN,NaN,NaN
5,3,'008,Albania,7011,Cost of fruits,6226,Value,PPP dollar per person per day,0.911,NaN,NaN,NaN
6,3,'008,Albania,7012,Cost of oils and fats,6226,Value,PPP dollar per person per day,0.089,NaN,NaN,NaN
7,3,'008,Albania,7005,Percentage of the population unable to afford ...,6121,Value,%,37.800,27.900,19.800,20.100
8,3,'008,Albania,7006,Number of people unable to afford a healthy di...,6132,Value,millions,1.100,0.800,0.600,0.600
9,4,'012,Algeria,7004,Cost of a healthy diet (PPP dollar per person ...,6226,Value,PPP dollar per person per day,3.763,3.822,3.796,3.760